[package]
name = "nibva"
version = "0.1.0"
description = "Local-first AI-friendly writing app"
authors = ["麦先生"]
edition = "2021"

[[bin]]
name = "Nibva"
path = "src/main.rs"

[lib]
name = "nibva_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "macos-private-api"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
notify = "8"
