import { EditorView } from "@codemirror/view";

export const editorTheme = EditorView.theme({
  "&": {
    height: "100%",
    color: "#1d1d1f",
    backgroundColor: "#ffffff",
    fontSize: "var(--editor-body-font-size, 18px)",
  },
  ".cm-scroller": {
    height: "100%",
    fontFamily: "var(--editor-font-family, -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', 'Microsoft YaHei', sans-serif)",
    lineHeight: "var(--editor-line-height, 1.76)",
    padding: "48px 0 0",
  },
  ".cm-content": {
    maxWidth: "760px",
    minHeight: "100%",
    margin: "0 auto",
    padding: "0 28px 128px",
    caretColor: "#0071e3",
  },
  ".cm-content ::selection": {
    backgroundColor: "rgb(0 113 227 / 22%)",
  },
  ".cm-selectionBackground": {
    backgroundColor: "rgb(0 113 227 / 14%) !important",
  },
  "&.cm-focused .cm-selectionBackground": {
    backgroundColor: "rgb(0 113 227 / 22%) !important",
  },
  "&.cm-focused .cm-cursor": {
    borderLeftColor: "#0071e3",
    borderLeftWidth: "2px",
  },
  ".cm-dropCursor": {
    borderLeftColor: "#0071e3",
  },
  ".cm-line": {
    padding: "0 2px var(--editor-paragraph-spacing, 0px)",
  },
  ".cm-table-line": {
    fontSize: "var(--editor-table-font-size, 15px)",
  },
  ".cm-heading-marker-widget": {
    display: "inline-block",
    width: "44px",
    marginLeft: "-50px",
    marginRight: "6px",
    overflow: "visible",
    color: "#d7d7dc",
    fontSize: "13px",
    fontFamily: "'SF Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
    fontWeight: "620",
    letterSpacing: "0",
    lineHeight: "inherit",
    pointerEvents: "none",
    textAlign: "right",
    verticalAlign: "baseline",
    whiteSpace: "pre",
  },
  ".cm-emphasis-rendered": {
    display: "inline-block",
    color: "#4f4f57",
    fontStyle: "normal",
    fontWeight: "520",
    transform: "skewX(-10deg)",
    transformOrigin: "left center",
  },
  ".cm-highlight-rendered": {
    borderRadius: "5px",
    padding: "0 3px",
    color: "#1d1d1f",
    backgroundColor: "#fff3a8",
    boxDecorationBreak: "clone",
    WebkitBoxDecorationBreak: "clone",
  },
  ".cm-underline-rendered": {
    textDecoration: "underline",
    textDecorationThickness: "1.2px",
    textUnderlineOffset: "2px",
  },
  ".cm-quote-line": {
    borderLeft: "3px solid #d7d7dd",
    borderRadius: "0",
    paddingLeft: "12px",
    color: "#5f6068",
    backgroundColor: "#f7f7f9",
  },
  ".cm-image-preview": {
    display: "inline-block",
    position: "relative",
    maxWidth: "100%",
    margin: "0",
    borderRadius: "8px",
  },
  ".cm-image-preview.selected img": {
    outline: "2px solid #0071e3",
    outlineOffset: "3px",
    boxShadow: "0 0 0 5px rgb(0 113 227 / 14%), 0 6px 18px rgb(0 0 0 / 12%)",
  },
  ".cm-image-preview.size-thumbnail img": {
    maxWidth: "160px",
    maxHeight: "120px",
  },
  ".cm-image-preview.size-small img": {
    maxWidth: "320px",
    maxHeight: "240px",
  },
  ".cm-image-preview.size-medium img": {
    maxWidth: "520px",
    maxHeight: "360px",
  },
  ".cm-image-preview.size-large img": {
    maxWidth: "100%",
    maxHeight: "520px",
  },
  ".cm-image-reference-line": {
    paddingBottom: "0",
  },
  ".cm-image-reference-line-hidden": {
    lineHeight: "0",
  },
  ".cm-image-reference-hidden": {
    fontSize: "0",
    lineHeight: "0",
    color: "transparent",
  },
  ".cm-image-reference-hidden *": {
    color: "transparent",
  },
  ".cm-image-preview img": {
    display: "block",
    maxWidth: "100%",
    maxHeight: "420px",
    borderRadius: "8px",
    objectFit: "contain",
    boxShadow: "0 1px 2px rgb(0 0 0 / 8%)",
  },
  ".cm-image-preview-action": {
    position: "absolute",
    top: "8px",
    right: "8px",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    border: "1px solid rgb(255 255 255 / 72%)",
    borderRadius: "999px",
    padding: "0",
    color: "#1d1d1f",
    backgroundColor: "rgb(255 255 255 / 86%)",
    boxShadow: "0 4px 14px rgb(0 0 0 / 14%)",
    cursor: "pointer",
    backdropFilter: "blur(14px) saturate(140%)",
  },
  ".cm-image-preview-action svg": {
    width: "16px",
    height: "16px",
    stroke: "currentColor",
  },
  ".cm-image-preview-action:hover": {
    backgroundColor: "rgb(255 255 255 / 96%)",
  },
  ".cm-image-preview:hover .cm-image-preview-action, .cm-image-preview.selected .cm-image-preview-action, .cm-image-preview.source-visible .cm-image-preview-action":
    {
      display: "flex",
    },
  ".cm-image-preview-error": {
    display: "inline-flex",
    maxWidth: "100%",
    margin: "8px 0 14px",
    borderRadius: "7px",
    padding: "8px 10px",
    color: "#6e6e73",
    backgroundColor: "#f5f5f7",
    fontSize: "13px",
    lineHeight: "1.35",
  },
  ".cm-image-context-menu": {
    position: "fixed",
    zIndex: "10000",
    minWidth: "148px",
    border: "1px solid rgb(0 0 0 / 12%)",
    borderRadius: "8px",
    padding: "5px 6px",
    color: "#1d1d1f",
    backgroundColor: "rgb(255 255 255 / 92%)",
    boxShadow: "0 12px 30px rgb(0 0 0 / 18%)",
    font: "13px -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', sans-serif",
    backdropFilter: "blur(22px) saturate(160%)",
  },
  ".cm-image-context-menu button": {
    display: "grid",
    gridTemplateColumns: "14px 1fr",
    alignItems: "center",
    columnGap: "4px",
    width: "100%",
    minHeight: "26px",
    border: "0",
    borderRadius: "5px",
    padding: "0 9px 0 3px",
    color: "inherit",
    backgroundColor: "transparent",
    font: "inherit",
    textAlign: "left",
    cursor: "default",
  },
  ".cm-image-context-menu button:hover": {
    backgroundColor: "#0071e3",
    color: "#ffffff",
  },
  ".cm-image-context-check": {
    display: "inline-block",
    width: "14px",
    color: "inherit",
    textAlign: "center",
  },
  ".cm-image-context-label": {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-image-context-menu-separator": {
    height: "1px",
    margin: "5px 10px",
    backgroundColor: "rgb(0 0 0 / 10%)",
  },
  ".cm-activeLine": {
    backgroundColor: "transparent",
  },
  "&.cm-focused": {
    outline: "none",
  },
  ".cm-panels": {
    color: "#1d1d1f",
    backgroundColor: "#fbfbfc",
    borderColor: "#ececf0",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: "13px",
  },
  ".cm-panel.cm-search": {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
  },
  ".cm-panel.cm-search input": {
    height: "28px",
    border: "1px solid #d7d7dd",
    borderRadius: "7px",
    padding: "0 8px",
    color: "#1d1d1f",
    backgroundColor: "#ffffff",
    outline: "none",
  },
  ".cm-panel.cm-search button": {
    minHeight: "28px",
    border: "1px solid #d7d7dd",
    borderRadius: "7px",
    padding: "0 8px",
    color: "#1d1d1f",
    backgroundColor: "#ffffff",
    font: "inherit",
  },
  ".cm-panel.cm-search button:hover": {
    backgroundColor: "#f2f2f4",
  },
  ".cm-searchMatch": {
    backgroundColor: "#fff3b0",
  },
  ".cm-searchMatch-selected": {
    backgroundColor: "#ffd85a",
  },
});
