/**
 * [INPUT]: 依赖 CodeMirror EditorView 与 themes/index.css 提供的 editor/menu 语义 Token
 * [OUTPUT]: 对外提供 editorTheme，包含跨工具栏焦点的选区高亮、自适应文末续写空间、坐标稳定的围栏代码、分隔线、GFM 表格、无序/任务列表、无伪分隔线的脚注及正常/失效图片预览反馈
 * [POS]: 编辑器 feature 的 CodeMirror 视觉边界，统一文稿排版与交互反馈；文本光标由原生 caret-color 表达而非自绘图层，编辑内容不用垂直 margin 或阅读/源码态行高突变破坏高度映射，也不用 hover 改写源码显隐语义
 * [PROTOCOL]: 变更时更新此头部，然后检查 AGENTS.md
 */
import { EditorView } from "@codemirror/view";

export const editorTheme = EditorView.theme({
  "&": {
    height: "100%",
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-bg)",
    fontSize: "var(--editor-body-font-size, 18px)",
  },
  ".cm-scroller": {
    height: "100%",
    fontFamily: "var(--editor-font-family, -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', 'Microsoft YaHei', sans-serif)",
    lineHeight: "var(--editor-line-height, 1.76)",
    padding: "80px 0 0",
  },
  ".cm-content": {
    maxWidth: "var(--editor-content-max-width)",
    minHeight: "100%",
    margin: "0 auto",
    padding: "0 var(--editor-content-gutter) clamp(180px, 24vh, 280px)",
    // 文本光标由浏览器原生绘制：它与文字在同一帧合成，中文 IME 组合期不会滞后
    caretColor: "var(--editor-accent)",
  },
  ".cm-content ::selection": {
    backgroundColor: "var(--editor-selection)",
  },
  ".cm-selectionBackground": {
    backgroundColor: "var(--editor-selection-soft) !important",
  },
  "&.cm-focused .cm-selectionBackground": {
    backgroundColor: "var(--editor-selection) !important",
  },
  ".cm-selection-toolbar-highlight": {
    backgroundColor: "var(--editor-selection)",
  },
  ".cm-selection-toolbar-layer": {
    pointerEvents: "none",
  },
  // 图片预览被选中时，文字光标与文字选区都必须让位给图片自身的选中反馈
  "&.cm-image-selection-active .cm-content": {
    caretColor: "transparent",
  },
  "&.cm-image-selection-active .cm-content ::selection": {
    backgroundColor: "transparent",
  },
  ".cm-dropCursor": {
    borderLeftColor: "var(--editor-accent)",
  },
  ".cm-line": {
    position: "relative",
    padding: "0 2px var(--editor-paragraph-spacing, 0px)",
  },
  ".cm-table-line": {
    boxSizing: "border-box",
    padding: "3px 12px",
    color: "var(--editor-code-text)",
    backgroundColor: "var(--editor-block-bg)",
    fontFamily: "'SF Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
    fontSize: "var(--editor-table-font-size, 15px)",
    lineHeight: "1.55",
  },
  ".cm-table-source-start": {
    marginTop: "0",
    borderRadius: "var(--radius-md) var(--radius-md) 0 0",
    paddingTop: "8px",
    fontWeight: "700",
  },
  ".cm-table-source-delimiter": {
    color: "var(--editor-muted)",
  },
  ".cm-table-source-end": {
    marginBottom: "0",
    borderRadius: "0 0 var(--radius-md) var(--radius-md)",
    paddingBottom: "8px",
  },
  ".cm-task-checkbox": {
    display: "inline-grid",
    position: "relative",
    boxSizing: "border-box",
    width: "17px",
    height: "17px",
    margin: "0 9px 0 0",
    border: "1.5px solid var(--editor-muted)",
    borderRadius: "5px",
    padding: "0",
    color: "var(--editor-bg)",
    backgroundColor: "transparent",
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
    verticalAlign: "-2px",
    placeItems: "center",
    cursor: "pointer",
  },
  ".cm-task-checkbox[data-checked='true']": {
    borderColor: "var(--editor-accent)",
    backgroundColor: "var(--editor-accent)",
  },
  ".cm-task-checkbox[data-checked='true']::after": {
    content: "''",
    position: "absolute",
    top: "2px",
    left: "5px",
    boxSizing: "border-box",
    width: "5px",
    height: "9px",
    borderRight: "2px solid currentColor",
    borderBottom: "2px solid currentColor",
    transform: "rotate(45deg)",
  },
  ".cm-task-checkbox:focus-visible": {
    outline: "2px solid var(--editor-accent)",
    outlineOffset: "2px",
  },
  ".cm-task-list-content-completed": {
    color: "var(--editor-muted)",
    textDecoration: "line-through",
    textDecorationThickness: "1px",
  },
  ".cm-table-widget": {
    display: "grid",
    boxSizing: "border-box",
    width: "100%",
    margin: "0",
    overflow: "hidden",
    border: "1px solid var(--editor-divider)",
    borderRadius: "var(--radius-md)",
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-bg)",
    fontFamily: "var(--editor-font-family)",
    fontSize: "var(--editor-table-font-size, 15px)",
    lineHeight: "1.5",
    cursor: "text",
  },
  ".cm-table-widget:focus-visible": {
    outline: "2px solid var(--editor-accent)",
    outlineOffset: "2px",
  },
  ".cm-table-widget-row": {
    display: "grid",
    gridTemplateColumns: "repeat(var(--cm-table-column-count), minmax(0, 1fr))",
  },
  ".cm-table-widget-row + .cm-table-widget-row": {
    borderTop: "1px solid var(--editor-divider)",
  },
  ".cm-table-widget-header": {
    backgroundColor: "var(--editor-block-bg)",
    fontWeight: "700",
  },
  ".cm-table-widget-cell": {
    minWidth: "0",
    padding: "8px 10px",
    overflowWrap: "anywhere",
  },
  ".cm-table-widget-cell + .cm-table-widget-cell": {
    borderLeft: "1px solid var(--editor-divider)",
  },
  ".cm-heading-level-1": {
    padding: "8px 2px 8px",
    color: "var(--editor-heading)",
    fontFamily: "var(--editor-heading-font-family, var(--editor-font-family))",
    lineHeight: "1.34",
  },
  ".cm-heading-level-2": {
    padding: "16px 2px 6px",
    color: "var(--editor-heading)",
    fontFamily: "var(--editor-heading-font-family, var(--editor-font-family))",
    lineHeight: "1.38",
  },
  ".cm-heading-level-3": {
    padding: "12px 2px 5px",
    color: "var(--editor-heading)",
    fontFamily: "var(--editor-heading-font-family, var(--editor-font-family))",
    lineHeight: "1.42",
  },
  ".cm-heading-level-4": {
    padding: "10px 2px 4px",
    color: "var(--editor-heading)",
    fontFamily: "var(--editor-heading-font-family, var(--editor-font-family))",
    lineHeight: "1.45",
  },
  ".cm-horizontal-rule-line, .cm-horizontal-rule-source-line": {
    position: "relative",
    padding: "0 2px",
  },
  ".cm-horizontal-rule-line::before": {
    content: "''",
    position: "absolute",
    left: "2px",
    right: "2px",
    top: "50%",
    height: "1px",
    backgroundColor: "var(--editor-divider)",
    transform: "translateY(-50%)",
    pointerEvents: "none",
  },
  ".cm-code-block-line": {
    boxSizing: "border-box",
    padding: "0 14px",
    color: "var(--editor-code-text)",
    backgroundColor: "var(--editor-block-bg)",
    fontFamily: "'SF Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
    fontSize: "0.86em",
    lineHeight: "1.65",
  },
  ".cm-code-block-start": {
    marginTop: "0",
    borderRadius: "var(--radius-md) var(--radius-md) 0 0",
    paddingTop: "8px",
  },
  ".cm-code-block-end": {
    marginBottom: "0",
    borderRadius: "0 0 var(--radius-md) var(--radius-md)",
    paddingBottom: "8px",
  },
  ".cm-code-block-boundary:not(.cm-code-block-source-active)": {
    minHeight: "0",
    fontSize: "0",
    lineHeight: "0",
  },
  ".cm-code-block-boundary.cm-code-block-source-active": {
    color: "var(--editor-muted)",
    fontSize: "0.72em",
    lineHeight: "1.5",
  },
  ".cm-code-block-start.cm-code-block-source-active": {
    paddingTop: "6px",
  },
  ".cm-code-block-end.cm-code-block-source-active": {
    paddingBottom: "6px",
  },
  ".cm-unordered-list-marker-rendered": {
    display: "inline-block",
    position: "relative",
    color: "transparent",
  },
  ".cm-unordered-list-marker-rendered::before": {
    content: '"•"',
    position: "absolute",
    inset: "0",
    color: "var(--editor-accent)",
    textAlign: "center",
    pointerEvents: "none",
    transform: "scale(1.32)",
    transformOrigin: "center",
  },
  ".cm-emphasis-rendered": {
    display: "inline-block",
    color: "var(--editor-emphasis)",
    fontStyle: "normal",
    fontWeight: "520",
    transform: "skewX(-10deg)",
    transformOrigin: "left center",
  },
  ".cm-strong-rendered": {
    color: "var(--editor-strong)",
    fontWeight: "800",
    WebkitTextStroke: "0.12px currentColor",
  },
  ".cm-highlight-rendered": {
    borderRadius: "var(--radius-sm)",
    padding: "0 3px",
    color: "var(--editor-highlight-text)",
    backgroundColor: "var(--editor-highlight-bg)",
    boxDecorationBreak: "clone",
    WebkitBoxDecorationBreak: "clone",
  },
  ".cm-footnote-reference-rendered": {
    color: "var(--editor-accent)",
    fontSize: "0.68em",
    fontWeight: "800",
    lineHeight: "0",
    verticalAlign: "super",
    cursor: "pointer",
  },
  ".cm-footnote-definition-line": {
    color: "var(--editor-muted)",
    fontSize: "0.78em",
    lineHeight: "1.65",
  },
  ".cm-footnote-definition-content": {
    color: "var(--editor-muted)",
  },
  ".cm-footnote-definition-label": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "24px",
    marginRight: "6px",
    border: "0",
    padding: "0",
    color: "var(--editor-accent)",
    background: "transparent",
    font: "inherit",
    fontSize: "0.76em",
    fontWeight: "800",
    lineHeight: "1",
    verticalAlign: "super",
    cursor: "pointer",
  },
  ".cm-underline-rendered": {
    "--cm-underline-thickness": "1.2px",
    borderBottom: "var(--cm-underline-thickness) solid var(--editor-accent)",
    boxDecorationBreak: "clone",
    WebkitBoxDecorationBreak: "clone",
  },
  ".cm-strong-rendered .cm-underline-rendered, .cm-underline-rendered:has(.cm-strong-rendered)": {
    "--cm-underline-thickness": "2px",
  },
  ".cm-strikethrough-rendered": {
    color: "var(--editor-muted)",
    textDecoration: "line-through",
    textDecorationThickness: "1.2px",
  },
  ".cm-strikethrough-rendered .cm-emphasis-rendered": {
    textDecoration: "line-through",
    textDecorationThickness: "1.2px",
  },
  ".cm-quote-line": {
    borderLeft: "3px solid var(--editor-quote-border)",
    borderRadius: "0",
    paddingLeft: "12px",
    color: "var(--editor-quote-text)",
    backgroundColor: "var(--editor-quote-bg)",
  },
  ".cm-image-preview": {
    display: "inline-block",
    position: "relative",
    maxWidth: "100%",
    margin: "0",
    borderRadius: "var(--radius-md)",
  },
  ".cm-image-reference-line-selected .cm-image-preview img": {
    outline: "2px solid var(--editor-accent)",
    outlineOffset: "3px",
    boxShadow: "var(--editor-image-selected-shadow)",
  },
  ".cm-image-preview.size-thumbnail img": {
    maxWidth: "160px",
    maxHeight: "120px",
  },
  ".cm-image-preview.size-small img": {
    maxWidth: "320px",
    maxHeight: "240px",
  },
  ".cm-image-preview.size-medium img": {
    maxWidth: "520px",
    maxHeight: "360px",
  },
  ".cm-image-preview.size-large img": {
    maxWidth: "100%",
    maxHeight: "520px",
  },
  ".cm-image-reference-line": {
    paddingBottom: "0",
  },
  ".cm-image-reference-line-hidden": {
    lineHeight: "0",
  },
  ".cm-image-reference-hidden": {
    fontSize: "0",
    lineHeight: "0",
    color: "transparent",
  },
  ".cm-image-reference-hidden *": {
    color: "transparent",
  },
  ".cm-image-preview img": {
    display: "block",
    maxWidth: "100%",
    maxHeight: "420px",
    borderRadius: "var(--radius-md)",
    objectFit: "contain",
    boxShadow: "var(--editor-image-shadow)",
  },
  ".cm-image-preview-action": {
    position: "absolute",
    top: "8px",
    right: "8px",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    border: "1px solid var(--editor-floating-border)",
    borderRadius: "var(--radius-full)",
    padding: "0",
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-floating-background)",
    boxShadow: "var(--editor-image-action-shadow)",
    cursor: "pointer",
    backdropFilter: "blur(14px) saturate(140%)",
  },
  ".cm-image-preview-action svg": {
    width: "16px",
    height: "16px",
    stroke: "currentColor",
  },
  ".cm-image-preview-action:hover": {
    backgroundColor: "var(--editor-floating-background-hover)",
  },
  ".cm-image-preview:hover .cm-image-preview-action, .cm-image-reference-line-selected .cm-image-preview-action, .cm-image-preview.source-visible .cm-image-preview-action":
    {
      display: "flex",
    },
  ".cm-image-preview-error": {
    display: "inline-flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "2px",
    maxWidth: "100%",
    margin: "0",
    border: "0",
    borderRadius: "var(--radius-md)",
    padding: "8px 10px",
    color: "var(--editor-muted)",
    backgroundColor: "var(--editor-block-bg)",
    font: "inherit",
    fontSize: "13px",
    lineHeight: "1.35",
    textAlign: "left",
    cursor: "pointer",
  },
  ".cm-image-preview-error-message": {
    overflowWrap: "anywhere",
  },
  ".cm-image-preview-error-hint": {
    color: "var(--foreground-tertiary)",
    fontSize: "12px",
  },
  ".cm-image-reference-line-selected .cm-image-preview-error": {
    outline: "2px solid var(--editor-accent)",
    outlineOffset: "3px",
  },
  ".cm-image-preview-error:hover": {
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-selection-soft)",
  },
  ".cm-image-preview-loading": {
    display: "inline-flex",
    minWidth: "180px",
    minHeight: "96px",
    alignItems: "center",
    justifyContent: "center",
    margin: "0",
    borderRadius: "var(--radius-md)",
    color: "var(--editor-muted)",
    backgroundColor: "var(--editor-block-bg)",
    fontSize: "13px",
  },
  ".cm-image-context-menu": {
    position: "fixed",
    zIndex: "10000",
    minWidth: "148px",
    border: "1px solid var(--menu-border)",
    borderRadius: "var(--menu-radius)",
    padding: "var(--menu-padding)",
    color: "var(--menu-foreground)",
    backgroundColor: "var(--menu-glass-background)",
    boxShadow: "var(--menu-shadow)",
    font: "13px -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', sans-serif",
    backdropFilter: "var(--menu-backdrop-filter)",
  },
  ".cm-image-context-menu button": {
    display: "grid",
    gridTemplateColumns: "14px 1fr",
    alignItems: "center",
    columnGap: "4px",
    width: "100%",
    minHeight: "26px",
    border: "0",
    borderRadius: "var(--menu-item-radius)",
    padding: "0 9px 0 3px",
    color: "inherit",
    backgroundColor: "transparent",
    font: "inherit",
    textAlign: "left",
    cursor: "default",
  },
  ".cm-image-context-menu button:hover": {
    backgroundColor: "var(--menu-hover)",
    color: "var(--menu-foreground)",
  },
  ".cm-image-context-menu button.danger-menu-item": {
    color: "var(--destructive)",
  },
  ".cm-image-context-menu button.danger-menu-item:hover": {
    backgroundColor: "var(--menu-danger-hover)",
    color: "var(--destructive)",
  },
  ".cm-image-context-check": {
    display: "inline-block",
    width: "14px",
    color: "var(--foreground-tertiary)",
    textAlign: "center",
  },
  ".cm-image-context-label": {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-image-context-menu-separator": {
    height: "1px",
    margin: "5px 10px",
    backgroundColor: "var(--menu-separator)",
  },
  ".cm-activeLine": {
    backgroundColor: "transparent",
  },
  "&.cm-focused": {
    outline: "none",
  },
  ".cm-panels": {
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-panel-bg)",
    borderColor: "var(--editor-divider)",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: "13px",
  },
  ".cm-panel.cm-search": {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
  },
  ".cm-panel.cm-search input": {
    height: "28px",
    border: "1px solid var(--editor-divider)",
    borderRadius: "var(--radius-md)",
    padding: "0 8px",
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-bg)",
    outline: "none",
  },
  ".cm-panel.cm-search button": {
    minHeight: "28px",
    border: "1px solid var(--editor-divider)",
    borderRadius: "var(--radius-md)",
    padding: "0 8px",
    color: "var(--editor-text)",
    backgroundColor: "var(--editor-bg)",
    font: "inherit",
  },
  ".cm-panel.cm-search button:hover": {
    backgroundColor: "var(--editor-block-bg)",
  },
  ".cm-searchMatch": {
    backgroundColor: "var(--editor-search-bg)",
  },
  ".cm-searchMatch-selected": {
    backgroundColor: "var(--editor-search-current)",
  },
});
