use crate::fs_paths::safe_file_segment;
use crate::models::{ProjectWritingBrief, WritingProject, WritingSheet};

pub(crate) fn markdown_h1_title(markdown: &str) -> Option<String> {
    markdown.lines().find_map(|line| {
        let trimmed = line.trim_start();
        let title = trimmed.strip_prefix("# ")?;
        let title = title.trim();
        if title.is_empty() {
            None
        } else {
            Some(title.to_string())
        }
    })
}

pub(crate) fn safe_visible_path_segment(title: &str, fallback: &str) -> String {
    let sanitized = title
        .trim()
        .chars()
        .map(|character| {
            if matches!(
                character,
                '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' | '\0'
            ) {
                '-'
            } else {
                character
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");
    let sanitized = sanitized.trim_matches(['.', '-']).to_string();
    if sanitized.is_empty() {
        safe_file_segment(fallback)
    } else {
        sanitized
    }
}

pub(crate) fn render_project_readme(project: &WritingProject) -> String {
    let mut output = vec![
        "---".to_string(),
        "nibvaProject: true".to_string(),
        format!("id: {}", quote_yaml(&project.id)),
        format!("title: {}", quote_yaml(&project.title)),
        format!("status: {}", quote_yaml(&project.status)),
        format!("targetPlatform: {}", quote_yaml(&project.target_platform)),
        format!("targetWords: {}", project.target_words),
        format!("updatedAt: {}", quote_yaml_timestamp(&project.updated_at)),
        format!(
            "tags: [{}]",
            project
                .tags
                .iter()
                .map(|tag| quote_yaml(tag))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        "---".to_string(),
        "".to_string(),
        format!("# {}", project.title),
        "".to_string(),
        project.description.clone(),
        "".to_string(),
        "## Project".to_string(),
        "".to_string(),
        format!("- Status: {}", project.status),
        format!("- Target platform: {}", project.target_platform),
        format!("- Target words: {}", project.target_words),
        format!("- Updated: {}", readable_timestamp(&project.updated_at)),
        "".to_string(),
    ];

    let brief_lines = render_project_writing_brief(&project.writing_brief);
    if !brief_lines.is_empty() {
        output.extend(brief_lines);
    }

    output.extend(["## Sheets".to_string(), "".to_string()]);

    for (index, sheet) in project.sheets.iter().enumerate() {
        output.push(format!(
            "{}. [{}]({}) - {} / {} words",
            index + 1,
            escape_markdown_link_text(&sheet.title),
            sheet_markdown_relative_path(project, sheet),
            sheet.sheet_type,
            sheet.target_words
        ));
        if !sheet.summary.trim().is_empty() {
            output.push(format!("   - {}", sheet.summary));
        }
    }

    if !project.groups.is_empty() {
        output.extend(["".to_string(), "## Groups".to_string(), "".to_string()]);
        for group in &project.groups {
            let sheet_count = project
                .sheets
                .iter()
                .filter(|sheet| sheet.group_id == group.id)
                .count();
            output.push(format!(
                "- {}: {} sheets",
                inline_markdown_text(&group.title),
                sheet_count
            ));
            if !group.description.trim().is_empty() {
                output.push(format!("  - {}", inline_markdown_text(&group.description)));
            }
        }
    }

    output.extend([
        "".to_string(),
        "## Project Folders".to_string(),
        "".to_string(),
        "- Writing groups are stored as folders in this project directory.".to_string(),
        "- [Assets](assets/)".to_string(),
        "- [References](references/)".to_string(),
        "- [Exports](exports/)".to_string(),
    ]);

    output.push("".to_string());
    output.join("\n")
}

pub(crate) fn render_project_toml(project: &WritingProject) -> String {
    let mut output = vec![
        "# Generated by Nibva for readable local project metadata.".to_string(),
        "# Markdown files in visible group folders are the durable writing content.".to_string(),
        "# App indexes live under the library-level .nibva/ folder.".to_string(),
        "".to_string(),
        "[nibva]".to_string(),
        "project = true".to_string(),
        "version = 1".to_string(),
        "".to_string(),
        "[project]".to_string(),
        format!("id = {}", quote_toml(&project.id)),
        format!("title = {}", quote_toml(&project.title)),
        format!("icon = {}", quote_toml(&project.icon)),
        format!("iconColor = {}", quote_toml(&project.icon_color)),
        format!("description = {}", quote_toml(&project.description)),
        format!("status = {}", quote_toml(&project.status)),
        format!("targetPlatform = {}", quote_toml(&project.target_platform)),
        format!("targetWords = {}", project.target_words),
        format!("updatedAt = {}", quote_toml(&project.updated_at)),
        format!("tags = {}", toml_string_array(&project.tags)),
        "".to_string(),
        "[writingBrief]".to_string(),
        format!("audience = {}", quote_toml(&project.writing_brief.audience)),
        format!("thesis = {}", quote_toml(&project.writing_brief.thesis)),
        format!("tone = {}", quote_toml(&project.writing_brief.tone)),
        format!(
            "publishingNotes = {}",
            quote_toml(&project.writing_brief.publishing_notes)
        ),
    ];

    for sheet in &project.sheets {
        output.extend([
            "".to_string(),
            "[[sheets]]".to_string(),
            format!("id = {}", quote_toml(&sheet.id)),
            format!("title = {}", quote_toml(&sheet.title)),
            format!("groupId = {}", quote_toml(&sheet.group_id)),
            format!("type = {}", quote_toml(&sheet.sheet_type)),
            format!("status = {}", quote_toml(&sheet.status)),
            format!("targetWords = {}", sheet.target_words),
            format!("summary = {}", quote_toml(&sheet.summary)),
            format!("createdAt = {}", quote_toml(&sheet.created_at)),
            format!("updatedAt = {}", quote_toml(&sheet.updated_at)),
            format!(
                "path = {}",
                quote_toml(&sheet_markdown_relative_path(project, sheet))
            ),
        ]);
    }

    for group in &project.groups {
        output.extend([
            "".to_string(),
            "[[groups]]".to_string(),
            format!("id = {}", quote_toml(&group.id)),
            format!("title = {}", quote_toml(&group.title)),
            format!("icon = {}", quote_toml(&group.icon)),
            format!("iconColor = {}", quote_toml(&group.icon_color)),
            format!("description = {}", quote_toml(&group.description)),
        ]);
    }

    for item in &project.publishing_checklist {
        output.extend([
            "".to_string(),
            "[[publishingChecklist]]".to_string(),
            format!("id = {}", quote_toml(&item.id)),
            format!("label = {}", quote_toml(&item.label)),
            format!("done = {}", item.done),
        ]);
    }

    for item in &project.export_history {
        output.extend([
            "".to_string(),
            "[[exportHistory]]".to_string(),
            format!("id = {}", quote_toml(&item.id)),
            format!("label = {}", quote_toml(&item.label)),
            format!("filename = {}", quote_toml(&item.filename)),
            format!("path = {}", quote_toml(&item.path)),
            format!("exportedAt = {}", quote_toml(&item.exported_at)),
            format!("sheetCount = {}", item.sheet_count),
            format!("wordCount = {}", item.word_count),
            format!("targetPlatform = {}", quote_toml(&item.target_platform)),
        ]);
    }

    output.push("".to_string());
    output.join("\n")
}

pub(crate) fn sheet_markdown_relative_path(
    project: &WritingProject,
    sheet: &WritingSheet,
) -> String {
    let group_title = project
        .groups
        .iter()
        .find(|group| group.id == sheet.group_id)
        .map(|group| group.title.as_str())
        .unwrap_or("默认组");
    format!(
        "{}/{}.md",
        safe_visible_path_segment(group_title, &sheet.group_id),
        safe_visible_path_segment(&sheet.title, &sheet.id)
    )
}

fn render_project_writing_brief(brief: &ProjectWritingBrief) -> Vec<String> {
    let fields = [
        ("Audience", brief.audience.trim()),
        ("Thesis", brief.thesis.trim()),
        ("Tone", brief.tone.trim()),
        ("Publishing notes", brief.publishing_notes.trim()),
    ];
    let filled_fields: Vec<(&str, &str)> = fields
        .iter()
        .copied()
        .filter(|(_, value)| !value.is_empty())
        .collect();

    if filled_fields.is_empty() {
        return vec![];
    }

    let mut output = vec!["## Writing Brief".to_string(), "".to_string()];
    for (label, value) in filled_fields {
        output.push(format!("- {}: {}", label, inline_markdown_text(value)));
    }
    output.push("".to_string());
    output
}

pub(crate) fn render_sheet_markdown(sheet: &WritingSheet) -> String {
    [
        "---".to_string(),
        "nibvaSheet: true".to_string(),
        format!("id: {}", quote_yaml(&sheet.id)),
        format!("title: {}", quote_yaml(&sheet.title)),
        format!("groupId: {}", quote_yaml(&sheet.group_id)),
        format!("type: {}", quote_yaml(&sheet.sheet_type)),
        format!("status: {}", quote_yaml(&sheet.status)),
        format!("targetWords: {}", sheet.target_words),
        format!("summary: {}", quote_yaml(&sheet.summary)),
        format!("createdAt: {}", quote_yaml_timestamp(&sheet.created_at)),
        format!("updatedAt: {}", quote_yaml_timestamp(&sheet.updated_at)),
        "---".to_string(),
        "".to_string(),
        sheet.body.trim_start_matches('\u{feff}').to_string(),
    ]
    .join("\n")
}

pub(crate) fn strip_nibva_frontmatter(markdown: &str) -> &str {
    let normalized = markdown.strip_prefix('\u{feff}').unwrap_or(markdown);
    if !normalized.starts_with("---\n") {
        return normalized;
    }

    let Some(end_index) = normalized[4..].find("\n---\n") else {
        return normalized;
    };
    let frontmatter = &normalized[4..4 + end_index];
    if !frontmatter
        .lines()
        .any(|line| line.trim() == "nibvaSheet: true")
    {
        return normalized;
    }

    normalized[4 + end_index + "\n---\n".len()..]
        .strip_prefix('\n')
        .unwrap_or(&normalized[4 + end_index + "\n---\n".len()..])
}

pub(crate) fn quote_yaml(value: &str) -> String {
    if can_write_plain_yaml_scalar(value) {
        return value.to_string();
    }

    quote_yaml_string(value)
}

fn quote_yaml_timestamp(value: &str) -> String {
    quote_yaml(&readable_timestamp(value))
}

fn readable_timestamp(value: &str) -> String {
    let bytes = value.as_bytes();
    if bytes.len() >= 19
        && bytes.get(4) == Some(&b'-')
        && bytes.get(7) == Some(&b'-')
        && matches!(bytes.get(10), Some(b'T' | b' '))
        && bytes.get(13) == Some(&b':')
        && bytes.get(16) == Some(&b':')
    {
        return format!("{} {}", &value[..10], &value[11..19]);
    }

    value.to_string()
}

fn can_write_plain_yaml_scalar(value: &str) -> bool {
    if value.is_empty() {
        return true;
    }
    if value.trim() != value || value.chars().any(|character| character.is_control()) {
        return false;
    }

    let lower = value.to_ascii_lowercase();
    if matches!(
        lower.as_str(),
        "true" | "false" | "null" | "~" | "nan" | ".nan" | "inf" | ".inf" | "-inf" | "-.inf"
    ) {
        return false;
    }
    if value.parse::<f64>().is_ok() {
        return false;
    }
    if value.contains(": ") || value.contains(" #") {
        return false;
    }
    if matches!(
        value.chars().next(),
        Some(
            '-' | '?'
                | ':'
                | ','
                | '['
                | ']'
                | '{'
                | '}'
                | '&'
                | '*'
                | '#'
                | '!'
                | '|'
                | '>'
                | '\''
                | '"'
                | '%'
                | '@'
                | '`'
        )
    ) {
        return false;
    }

    true
}

fn quote_yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

pub(crate) fn quote_toml(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{08}' => output.push_str("\\b"),
            '\u{0c}' => output.push_str("\\f"),
            value if value.is_control() => output.push_str(&format!("\\u{:04X}", value as u32)),
            value => output.push(value),
        }
    }
    output.push('"');
    output
}

fn toml_string_array(values: &[String]) -> String {
    format!(
        "[{}]",
        values
            .iter()
            .map(|value| quote_toml(value))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn escape_markdown_link_text(value: &str) -> String {
    value.replace('[', "\\[").replace(']', "\\]")
}

fn inline_markdown_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_h1_title_reads_first_h1() {
        assert_eq!(
            markdown_h1_title("intro\n# Title\n## Child"),
            Some("Title".to_string())
        );
        assert_eq!(markdown_h1_title("#   "), None);
    }

    #[test]
    fn safe_visible_path_segment_keeps_readable_titles() {
        assert_eq!(
            safe_visible_path_segment(" 第一章 / 起点 ", "fallback"),
            "第一章 - 起点"
        );
        assert_eq!(
            safe_visible_path_segment("...", "fallback-id"),
            "fallback-id"
        );
    }

    #[test]
    fn strip_nibva_frontmatter_removes_only_nibva_metadata() {
        let rendered = "---\nnibvaSheet: true\nid: a\n---\n\n# Body";
        assert_eq!(strip_nibva_frontmatter(rendered), "# Body");

        let user_markdown = "---\ntitle: User Metadata\n---\n\n# Keep";
        assert_eq!(strip_nibva_frontmatter(user_markdown), user_markdown);
    }

    #[test]
    fn quote_toml_escapes_control_characters() {
        assert_eq!(
            quote_toml("A \"quote\"\nC:\\Path"),
            "\"A \\\"quote\\\"\\nC:\\\\Path\""
        );
    }

    #[test]
    fn quote_yaml_prefers_plain_scalars_when_safe() {
        assert_eq!(quote_yaml("测试卡片"), "测试卡片");
        assert_eq!(quote_yaml("2026-07-04 11:00:00"), "2026-07-04 11:00:00");
        assert_eq!(quote_yaml("A: value"), "\"A: value\"");
        assert_eq!(quote_yaml("#007aff"), "\"#007aff\"");
    }
}
