//! [INPUT]: 依赖 fs_paths 安全文件段、写作库 models、serde_json/serde_yaml 与确定性映射结构
//! [OUTPUT]: 向 crate 提供按应用级目标隔离的文章发布身份可逆持久化、Markdown 渲染/剥离及路径规范化能力
//! [POS]: native 共享基础层，为多个领域提供序列化、路径、Markdown 或系统能力
//! [PROTOCOL]: 变更时更新此头部，然后检查 AGENTS.md
use crate::fs_paths::safe_file_segment;
use crate::models::{ProjectWritingBrief, WritingProject, WritingSheet};
use serde_json::Value as JsonValue;
use serde_yaml::{Mapping as YamlMapping, Value as YamlValue};
use std::collections::BTreeMap;

pub(crate) fn markdown_h1_title(markdown: &str) -> Option<String> {
    markdown.lines().find_map(|line| {
        let trimmed = line.trim_start();
        let title = trimmed.strip_prefix("# ")?;
        let title = title.trim();
        if title.is_empty() {
            None
        } else {
            Some(title.to_string())
        }
    })
}

pub(crate) fn safe_visible_path_segment(title: &str, fallback: &str) -> String {
    let sanitized = title
        .trim()
        .chars()
        .map(|character| {
            if matches!(
                character,
                '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' | '\0'
            ) {
                '-'
            } else {
                character
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");
    let sanitized = sanitized.trim_matches(['.', '-']).to_string();
    if sanitized.is_empty() {
        safe_file_segment(fallback)
    } else {
        sanitized
    }
}

pub(crate) fn render_project_readme(project: &WritingProject) -> String {
    let mut output = vec![
        "---".to_string(),
        "lobyProject: true".to_string(),
        format!("id: {}", quote_yaml(&project.id)),
        format!("title: {}", quote_yaml(&project.title)),
        format!("goalEnabled: {}", project.project_goal.enabled),
        format!("goalUnit: {}", quote_yaml(&project.project_goal.unit)),
        format!("goalTarget: {}", project.project_goal.target),
        format!("updatedAt: {}", quote_yaml_timestamp(&project.updated_at)),
        "---".to_string(),
        "".to_string(),
        format!("# {}", project.title),
        "".to_string(),
        "## Project".to_string(),
        "".to_string(),
        format!(
            "- Goal: {} {}",
            project.project_goal.target,
            if project.project_goal.unit == "articles" {
                "articles"
            } else {
                "words"
            }
        ),
        format!("- Updated: {}", readable_timestamp(&project.updated_at)),
        "".to_string(),
    ];

    let brief_lines = render_project_writing_brief(&project.writing_brief);
    if !brief_lines.is_empty() {
        output.extend(brief_lines);
    }

    output.extend(["## Sheets".to_string(), "".to_string()]);

    for (index, sheet) in project.sheets.iter().enumerate() {
        output.push(format!(
            "{}. [{}]({}) - {} words",
            index + 1,
            escape_markdown_link_text(&sheet.title),
            sheet_markdown_relative_path(project, sheet),
            sheet.target_words
        ));
        if !sheet.summary.trim().is_empty() {
            output.push(format!("   - {}", sheet.summary));
        }
    }

    if !project.groups.is_empty() {
        output.extend(["".to_string(), "## Groups".to_string(), "".to_string()]);
        for group in &project.groups {
            let sheet_count = project
                .sheets
                .iter()
                .filter(|sheet| sheet.group_id == group.id)
                .count();
            output.push(format!(
                "- {}: {} sheets",
                inline_markdown_text(&group.title),
                sheet_count
            ));
            if !group.description.trim().is_empty() {
                output.push(format!("  - {}", inline_markdown_text(&group.description)));
            }
        }
    }

    output.extend([
        "".to_string(),
        "## Project Folders".to_string(),
        "".to_string(),
        "- Writing groups are stored as folders in this project directory.".to_string(),
        "- [Assets](assets/)".to_string(),
        "- [References](references/)".to_string(),
        "- [Exports](exports/)".to_string(),
    ]);

    output.push("".to_string());
    output.join("\n")
}

pub(crate) fn render_project_toml(project: &WritingProject) -> String {
    let mut output = vec![
        "# Generated by Loby for readable local project metadata.".to_string(),
        "# Markdown files in visible group folders are the durable writing content.".to_string(),
        "# App indexes live under the library-level .loby/ folder.".to_string(),
        "".to_string(),
        "[loby]".to_string(),
        "project = true".to_string(),
        "version = 1".to_string(),
        "".to_string(),
        "[project]".to_string(),
        format!("id = {}", quote_toml(&project.id)),
        format!("title = {}", quote_toml(&project.title)),
        format!("icon = {}", quote_toml(&project.icon)),
        format!("iconColor = {}", quote_toml(&project.icon_color)),
        format!("status = {}", quote_toml(&project.status)),
        format!("updatedAt = {}", quote_toml(&project.updated_at)),
        format!("archivedAt = {}", quote_toml(&project.archived_at)),
        "".to_string(),
        "[projectGoal]".to_string(),
        format!("enabled = {}", project.project_goal.enabled),
        format!("unit = {}", quote_toml(&project.project_goal.unit)),
        format!("target = {}", project.project_goal.target),
        "".to_string(),
        "[writingBrief]".to_string(),
        format!("audience = {}", quote_toml(&project.writing_brief.audience)),
        format!("thesis = {}", quote_toml(&project.writing_brief.thesis)),
        format!("tone = {}", quote_toml(&project.writing_brief.tone)),
        format!(
            "publishingNotes = {}",
            quote_toml(&project.writing_brief.publishing_notes)
        ),
    ];

    for definition in &project.document_property_definitions {
        output.extend([
            "".to_string(),
            "[[documentPropertyDefinitions]]".to_string(),
            format!("id = {}", quote_toml(&definition.id)),
            format!("key = {}", quote_toml(&definition.key)),
            format!("label = {}", quote_toml(&definition.label)),
            format!("type = {}", quote_toml(&definition.field_type)),
            format!("description = {}", quote_toml(&definition.description)),
            format!("showWhenEmpty = {}", definition.show_when_empty),
            format!("locked = {}", definition.locked),
            format!(
                "defaultValueJson = {}",
                quote_toml(
                    &definition
                        .default_value
                        .as_ref()
                        .map(JsonValue::to_string)
                        .unwrap_or_default()
                )
            ),
            format!(
                "optionsJson = {}",
                quote_toml(
                    &serde_json::to_string(&definition.options)
                        .unwrap_or_else(|_| "[]".to_string())
                )
            ),
        ]);
    }

    for sheet in &project.sheets {
        output.extend([
            "".to_string(),
            "[[sheets]]".to_string(),
            format!("id = {}", quote_toml(&sheet.id)),
            format!("title = {}", quote_toml(&sheet.title)),
            format!("groupId = {}", quote_toml(&sheet.group_id)),
            format!("status = {}", quote_toml(&sheet.status)),
            format!("tags = {}", toml_string_array(&sheet.tags)),
            format!("targetWords = {}", sheet.target_words),
            format!("summary = {}", quote_toml(&sheet.summary)),
            format!("createdAt = {}", quote_toml(&sheet.created_at)),
            format!("updatedAt = {}", quote_toml(&sheet.updated_at)),
            format!("completedAt = {}", quote_toml(&sheet.completed_at)),
            format!(
                "path = {}",
                quote_toml(&sheet_markdown_relative_path(project, sheet))
            ),
        ]);
    }

    for group in &project.groups {
        output.extend([
            "".to_string(),
            "[[groups]]".to_string(),
            format!("id = {}", quote_toml(&group.id)),
            format!("title = {}", quote_toml(&group.title)),
            format!("icon = {}", quote_toml(&group.icon)),
            format!("iconColor = {}", quote_toml(&group.icon_color)),
            format!("description = {}", quote_toml(&group.description)),
        ]);
    }

    for item in &project.publishing_checklist {
        output.extend([
            "".to_string(),
            "[[publishingChecklist]]".to_string(),
            format!("id = {}", quote_toml(&item.id)),
            format!("label = {}", quote_toml(&item.label)),
            format!("done = {}", item.done),
        ]);
    }

    for item in &project.export_history {
        output.extend([
            "".to_string(),
            "[[exportHistory]]".to_string(),
            format!("id = {}", quote_toml(&item.id)),
            format!("label = {}", quote_toml(&item.label)),
            format!("filename = {}", quote_toml(&item.filename)),
            format!("path = {}", quote_toml(&item.path)),
            format!("exportedAt = {}", quote_toml(&item.exported_at)),
            format!("sheetCount = {}", item.sheet_count),
            format!("wordCount = {}", item.word_count),
            format!("targetPlatform = {}", quote_toml(&item.target_platform)),
        ]);
    }

    output.push("".to_string());
    output.join("\n")
}

pub(crate) fn sheet_markdown_relative_path(
    project: &WritingProject,
    sheet: &WritingSheet,
) -> String {
    let group_title = project
        .groups
        .iter()
        .find(|group| group.id == sheet.group_id)
        .map(|group| group.title.as_str())
        .unwrap_or("待整理");
    format!(
        "{}/{}.md",
        safe_visible_path_segment(group_title, &sheet.group_id),
        safe_visible_path_segment(&sheet.title, &sheet.id)
    )
}

fn render_project_writing_brief(brief: &ProjectWritingBrief) -> Vec<String> {
    let fields = [
        ("Audience", brief.audience.trim()),
        ("Thesis", brief.thesis.trim()),
        ("Tone", brief.tone.trim()),
        ("Publishing notes", brief.publishing_notes.trim()),
    ];
    let filled_fields: Vec<(&str, &str)> = fields
        .iter()
        .copied()
        .filter(|(_, value)| !value.is_empty())
        .collect();

    if filled_fields.is_empty() {
        return vec![];
    }

    let mut output = vec!["## Writing Brief".to_string(), "".to_string()];
    for (label, value) in filled_fields {
        output.push(format!("- {}: {}", label, inline_markdown_text(value)));
    }
    output.push("".to_string());
    output
}

pub(crate) fn render_sheet_markdown(sheet: &WritingSheet) -> String {
    let mut frontmatter = YamlMapping::new();
    for (key, value) in &sheet.properties {
        if is_reserved_sheet_property(key) {
            continue;
        }
        if let Ok(value) = serde_yaml::to_value(value) {
            frontmatter.insert(YamlValue::String(key.clone()), value);
        }
    }

    frontmatter.insert(
        YamlValue::String("title".to_string()),
        YamlValue::String(sheet.title.clone()),
    );
    frontmatter.insert(
        YamlValue::String("lobySheet".to_string()),
        YamlValue::Bool(true),
    );
    frontmatter.insert(
        YamlValue::String("tags".to_string()),
        serde_yaml::to_value(&sheet.tags).unwrap_or_else(|_| YamlValue::Sequence(Vec::new())),
    );

    let mut loby = YamlMapping::new();
    insert_yaml_string(&mut loby, "id", &sheet.id);
    insert_yaml_string(&mut loby, "groupId", &sheet.group_id);
    insert_yaml_string(&mut loby, "status", &sheet.status);
    loby.insert(
        YamlValue::String("targetWords".to_string()),
        YamlValue::Number(sheet.target_words.into()),
    );
    insert_yaml_string(&mut loby, "summary", &sheet.summary);
    insert_yaml_string(
        &mut loby,
        "createdAt",
        &readable_timestamp(&sheet.created_at),
    );
    insert_yaml_string(
        &mut loby,
        "updatedAt",
        &readable_timestamp(&sheet.updated_at),
    );
    if !sheet.archived_at.is_empty() {
        insert_yaml_string(
            &mut loby,
            "archivedAt",
            &readable_timestamp(&sheet.archived_at),
        );
    }
    if !sheet.completed_at.is_empty() {
        insert_yaml_string(
            &mut loby,
            "completedAt",
            &readable_timestamp(&sheet.completed_at),
        );
    }
    if !sheet.publications.is_empty() {
        if let Ok(value) = serde_yaml::to_value(&sheet.publications) {
            loby.insert(YamlValue::String("publications".to_string()), value);
        }
    }
    frontmatter.insert(
        YamlValue::String("loby".to_string()),
        YamlValue::Mapping(loby),
    );

    let serialized = serde_yaml::to_string(&frontmatter).unwrap_or_default();
    format!(
        "---\n{}---\n\n{}",
        serialized,
        sheet.body.trim_start_matches('\u{feff}')
    )
}

pub(crate) fn strip_loby_frontmatter(markdown: &str) -> &str {
    let normalized = markdown.strip_prefix('\u{feff}').unwrap_or(markdown);
    split_frontmatter(normalized)
        .map(|(_, body)| body)
        .unwrap_or(normalized)
}

pub(crate) fn sheet_frontmatter_value(raw: &str, key: &str) -> Option<String> {
    let (frontmatter, _) = split_frontmatter(raw)?;
    let mapping = serde_yaml::from_str::<YamlMapping>(frontmatter).ok()?;
    let key_value = YamlValue::String(key.to_string());
    let value = mapping
        .get(YamlValue::String("loby".to_string()))
        .and_then(YamlValue::as_mapping)
        .and_then(|loby| loby.get(&key_value))
        .or_else(|| mapping.get(&key_value))?;
    yaml_scalar_string(value)
}

pub(crate) fn sheet_frontmatter_properties(raw: &str) -> BTreeMap<String, JsonValue> {
    let Some((frontmatter, _)) = split_frontmatter(raw) else {
        return BTreeMap::new();
    };
    let Ok(mapping) = serde_yaml::from_str::<YamlMapping>(frontmatter) else {
        return BTreeMap::new();
    };
    mapping
        .iter()
        .filter_map(|(key, value)| {
            let key = key.as_str()?.to_string();
            if is_reserved_sheet_property(&key) {
                return None;
            }
            serde_json::to_value(value).ok().map(|value| (key, value))
        })
        .collect()
}

pub(crate) fn sheet_frontmatter_tags(raw: &str) -> Vec<String> {
    let Some((frontmatter, _)) = split_frontmatter(raw) else {
        return Vec::new();
    };
    let Ok(mapping) = serde_yaml::from_str::<YamlMapping>(frontmatter) else {
        return Vec::new();
    };
    mapping
        .get(YamlValue::String("tags".to_string()))
        .and_then(YamlValue::as_sequence)
        .map(|values| {
            values
                .iter()
                .filter_map(YamlValue::as_str)
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

pub(crate) fn sheet_frontmatter_publications(
    raw: &str,
) -> BTreeMap<String, crate::models::PublishingTargetPublication> {
    let Some((frontmatter, _)) = split_frontmatter(raw) else {
        return BTreeMap::new();
    };
    let Ok(mapping) = serde_yaml::from_str::<YamlMapping>(frontmatter) else {
        return BTreeMap::new();
    };
    let Some(loby) = mapping
        .get(YamlValue::String("loby".to_string()))
        .and_then(YamlValue::as_mapping)
    else {
        return BTreeMap::new();
    };
    if let Some(value) = loby.get(YamlValue::String("publications".to_string())) {
        return serde_yaml::from_value(value.clone()).unwrap_or_default();
    }
    let mut publications = BTreeMap::new();
    if let Some(publication) = loby
        .get(YamlValue::String("blog".to_string()))
        .and_then(|value| serde_yaml::from_value(value.clone()).ok())
    {
        publications.insert("github-blog".to_string(), publication);
    }
    publications
}

fn split_frontmatter(markdown: &str) -> Option<(&str, &str)> {
    let normalized = markdown.strip_prefix('\u{feff}').unwrap_or(markdown);
    if !normalized.starts_with("---\n") {
        return None;
    }
    let end_index = normalized[4..].find("\n---\n")?;
    let frontmatter = &normalized[4..4 + end_index];
    let body = &normalized[4 + end_index + "\n---\n".len()..];
    Some((frontmatter, body.strip_prefix('\n').unwrap_or(body)))
}

fn is_reserved_sheet_property(key: &str) -> bool {
    matches!(
        key,
        "loby"
            | "lobySheet"
            | "id"
            | "title"
            | "groupId"
            | "type"
            | "status"
            | "tags"
            | "targetWords"
            | "summary"
            | "createdAt"
            | "updatedAt"
            | "archivedAt"
            | "completedAt"
    )
}

fn insert_yaml_string(mapping: &mut YamlMapping, key: &str, value: &str) {
    mapping.insert(
        YamlValue::String(key.to_string()),
        YamlValue::String(value.to_string()),
    );
}

fn yaml_scalar_string(value: &YamlValue) -> Option<String> {
    match value {
        YamlValue::String(value) => Some(value.clone()),
        YamlValue::Number(value) => Some(value.to_string()),
        YamlValue::Bool(value) => Some(value.to_string()),
        YamlValue::Null => Some(String::new()),
        _ => None,
    }
}

pub(crate) fn quote_yaml(value: &str) -> String {
    if can_write_plain_yaml_scalar(value) {
        return value.to_string();
    }

    quote_yaml_string(value)
}

fn quote_yaml_timestamp(value: &str) -> String {
    quote_yaml(&readable_timestamp(value))
}

fn readable_timestamp(value: &str) -> String {
    let bytes = value.as_bytes();
    if bytes.len() >= 19
        && bytes.get(4) == Some(&b'-')
        && bytes.get(7) == Some(&b'-')
        && matches!(bytes.get(10), Some(b'T' | b' '))
        && bytes.get(13) == Some(&b':')
        && bytes.get(16) == Some(&b':')
    {
        return format!("{} {}", &value[..10], &value[11..19]);
    }

    value.to_string()
}

fn can_write_plain_yaml_scalar(value: &str) -> bool {
    if value.is_empty() {
        return true;
    }
    if value.trim() != value || value.chars().any(|character| character.is_control()) {
        return false;
    }

    let lower = value.to_ascii_lowercase();
    if matches!(
        lower.as_str(),
        "true" | "false" | "null" | "~" | "nan" | ".nan" | "inf" | ".inf" | "-inf" | "-.inf"
    ) {
        return false;
    }
    if value.parse::<f64>().is_ok() {
        return false;
    }
    if value.contains(": ") || value.contains(" #") {
        return false;
    }
    if matches!(
        value.chars().next(),
        Some(
            '-' | '?'
                | ':'
                | ','
                | '['
                | ']'
                | '{'
                | '}'
                | '&'
                | '*'
                | '#'
                | '!'
                | '|'
                | '>'
                | '\''
                | '"'
                | '%'
                | '@'
                | '`'
        )
    ) {
        return false;
    }

    true
}

fn quote_yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

pub(crate) fn quote_toml(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{08}' => output.push_str("\\b"),
            '\u{0c}' => output.push_str("\\f"),
            value if value.is_control() => output.push_str(&format!("\\u{:04X}", value as u32)),
            value => output.push(value),
        }
    }
    output.push('"');
    output
}

fn toml_string_array(values: &[String]) -> String {
    format!(
        "[{}]",
        values
            .iter()
            .map(|value| quote_toml(value))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn escape_markdown_link_text(value: &str) -> String {
    value.replace('[', "\\[").replace(']', "\\]")
}

fn inline_markdown_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_h1_title_reads_first_h1() {
        assert_eq!(
            markdown_h1_title("intro\n# Title\n## Child"),
            Some("Title".to_string())
        );
        assert_eq!(markdown_h1_title("#   "), None);
    }

    #[test]
    fn safe_visible_path_segment_keeps_readable_titles() {
        assert_eq!(
            safe_visible_path_segment(" 第一章 / 起点 ", "fallback"),
            "第一章 - 起点"
        );
        assert_eq!(
            safe_visible_path_segment("...", "fallback-id"),
            "fallback-id"
        );
    }

    #[test]
    fn strip_frontmatter_removes_metadata_and_keeps_body() {
        let rendered = "---\nlobySheet: true\nid: a\n---\n\n# Body";
        assert_eq!(strip_loby_frontmatter(rendered), "# Body");

        let user_markdown = "---\ntitle: User Metadata\n---\n\n# Keep";
        assert_eq!(strip_loby_frontmatter(user_markdown), "# Keep");
    }

    #[test]
    fn quote_toml_escapes_control_characters() {
        assert_eq!(
            quote_toml("A \"quote\"\nC:\\Path"),
            "\"A \\\"quote\\\"\\nC:\\\\Path\""
        );
    }

    #[test]
    fn quote_yaml_prefers_plain_scalars_when_safe() {
        assert_eq!(quote_yaml("测试卡片"), "测试卡片");
        assert_eq!(quote_yaml("2026-07-04 11:00:00"), "2026-07-04 11:00:00");
        assert_eq!(quote_yaml("A: value"), "\"A: value\"");
        assert_eq!(quote_yaml("#007aff"), "\"#007aff\"");
    }
}
